name: bible_quest
description: A Bible trivia game to grow in faith and knowledge.
version: 1.0.0+1
license: Proprietary
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0' # Compatible Flutter SDK range

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0 # Add this
  audioplayers: ^5.2.0 # For quiz_screen.dart
  url_launcher: ^6.1.10 # For home_screen.dart
  share_plus: ^7.2.0 # For home_screen.dart
  http_client: ^1.5.3
  http: ^1.2.1
  crypto: ^3.0.5
  uuid: ^4.4.2
  shared_preferences: ^2.2.0
  connectivity_plus: ^5.0.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # For code linting (optional)

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/questions.json
    - assets/fallback_questions.json


    