name: bible_quest
description: A Bible trivia game to grow in faith and knowledge.
version: 1.0.1+2
license: Proprietary
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  audioplayers: ^5.2.1
  url_launcher: ^6.1.10
  share_plus: ^6.3.4
  http_client: ^1.5.3
  http: ^1.1.0
  crypto: ^3.0.3
  uuid: ^3.0.7
  shared_preferences: ^2.2.0
  connectivity_plus: ^4.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

dependency_overrides:
  win32: ^5.0.0
  collection: ^1.17.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/sounds/
    - assets/questions.json
    - assets/fallback_questions.json

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FF9800"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_padding: true
  adaptive_icon_foreground_scale: 0.8
  adaptive_icon_foreground_scale_x: 0.85
  adaptive_icon_foreground_scale_y: 0.85
  adaptive_icon_foreground_offset_x: -0.05  # Move 5% to the left
  adaptive_icon_foreground_offset_y: 0.0


    